-- jy_schema
--
-- SchemaStore for JSON & Yaml
--
-- https://github.com/b0o/SchemaStore.nvim

-- local function detect_and_notify_linter()
--   local filetype = vim.bo.filetype
--   local filepath = vim.fn.expand('%:p')
--   local filename = vim.fn.fnamemodify(filepath, ':t')
--
--   if filetype ~= 'json' and filetype ~= 'yaml' then
--     vim.notify("Current file is not JSON or YAML", vim.log.levels.WARN)
--     return
--   end
--
--   -- Function to get LSP client for the current buffer
--   local function get_lsp_client()
--     local buf_ft = vim.api.nvim_buf_get_option(0, 'filetype')
--     local clients = vim.lsp.get_clients()
--     for _, client in pairs(clients) do
--       local filetypes = client.config.filetypes
--       AppendLog("**********************************")
--       AppendLog(ToString(filetypes))
--       AppendLog("**********************************")
--       if filetypes and vim.tbl_contains(filetypes, buf_ft) then
--         return client
--       end
--     end
--     return nil
--   end
--
--   -- Query LSP server
--   local client = get_lsp_client()
--   if client then
--     client.request('workspace/configuration', { items = {{ section = "yaml" }} }, function(err, result)
--       if err then
--         vim.notify("Error querying LSP: " .. err.message, vim.log.levels.ERROR)
--       elseif result and result[1] and result[1].schemas then
--         local schemas = result[1].schemas
--         for _, schema in ipairs(schemas) do
--           if schema.fileMatch then
--             for _, pattern in ipairs(schema.fileMatch) do
--               local lua_pattern = '^' .. pattern:gsub('%.', '%%.'):gsub('*', '.*') .. '$'
--               if filename:match(lua_pattern) or filepath:match(lua_pattern) then
--                 vim.notify("LSP is using schema: " .. schema.name, vim.log.levels.INFO)
--                 return
--               end
--             end
--           end
--         end
--         vim.notify("LSP has schemas configured, but none match this file", vim.log.levels.WARN)
--       else
--         vim.notify("LSP doesn't have schema configuration or isn't providing it", vim.log.levels.WARN)
--       end
--     end)
--   else
--     vim.notify("No active LSP client found for this file", vim.log.levels.WARN)
--   end
--
--   -- SchemaStore check (as before)
--   local schema_store = require('schemastore')
--   local schemas = schema_store.json.schemas()
--
--   for _, schema in ipairs(schemas) do
--     if schema.fileMatch then
--       for _, pattern in ipairs(schema.fileMatch) do
--         local lua_pattern = '^' .. pattern:gsub('%.', '%%.'):gsub('*', '.*') .. '$'
--         if filename:match(lua_pattern) or filepath:match(lua_pattern) then
--           vim.notify("SchemaStore suggests schema: " .. schema.name, vim.log.levels.INFO)
--           return
--         end
--       end
--     end
--   end
--
--   vim.notify("No matching schema found in SchemaStore for this file", vim.log.levels.WARN)
-- end
--
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = {"json", "yaml"},
--   callback = function()
--     vim.defer_fn(detect_and_notify_linter, 2000)
--   end
-- })

---------------------------------------------------

local opts = {
  'b0o/SchemaStore.nvim',
}

return opts
