#!/usr/bin/env bash 

# Regen 
# 
# Run `Snipcon` on each `<lang>.snippet` file, 
# and direct output to `json/<lang>.json`.

cd "$(dirname "$0")" || exit # run from the script directory
rm -f json/*json             # remove existing JSON files

# --- run the Snipcon converter on each snippet file
